import streamlit as st
import pandas as pd
import json
import urllib.request
from databricks.vector_search.client import VectorSearchClient
from databricks.sdk import WorkspaceClient
from databricks import sql

# ── Page config ──────────────────────────────────────────────
st.set_page_config(
    page_title="E-Commerce AI Assistant",
    page_icon="🛍️",
    layout="wide"
)

# ── Helpers ──────────────────────────────────────────────────
@st.cache_resource
def get_clients():
    w = WorkspaceClient()
    vsc = VectorSearchClient()
    return w, vsc

@st.cache_resource
def get_sql_connection():
    """Create a connection to the SQL warehouse"""
    w = WorkspaceClient()
    connection = sql.connect(
        server_hostname=w.config.host.replace("https://", ""),
        http_path=f"/sql/1.0/warehouses/96b47259ff35cccf",
        access_token=w.config.token
    )
    return connection

def query_table(table_name):
    """Execute SELECT * FROM table and return as pandas DataFrame"""
    conn = get_sql_connection()
    cursor = conn.cursor()
    cursor.execute(f"SELECT * FROM {table_name}")
    
    # Fetch results and column names
    columns = [desc[0] for desc in cursor.description]
    rows = cursor.fetchall()
    cursor.close()
    
    # Convert to pandas DataFrame
    return pd.DataFrame(rows, columns=columns)

def call_llm(prompt, token, host):
    data = json.dumps({
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 400
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{host}/serving-endpoints/databricks-meta-llama-3-3-70b-instruct/invocations",
        data=data,
        headers={
            "Authorization": f"Bearer {token}",
            "Content-Type": "application/json"
        }
    )
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())["choices"][0]["message"]["content"]

def rag_answer(question, vsc, token, host):
    index = vsc.get_index(
        endpoint_name="ecommerce_vs_endpoint",
        index_name="ecommerce_demo.sales.policy_chunks_index"
    )
    results = index.similarity_search(
        query_text=question,
        columns=["title", "content"],
        num_results=3
    )
    context = ""
    sources = []
    for r in results["result"]["data_array"]:
        title, content = r[0], r[1]
        context += f"[{title}]: {content}\n"
        if title not in sources:
            sources.append(title)

    prompt = f"""You are a helpful e-commerce customer support assistant.
Answer using ONLY the context below. Be concise and specific.
If not in context, say "I don't have information about that."

Context:
{context}

Question: {question}
Answer:"""
    return call_llm(prompt, token, host), sources

# ── Sidebar ──────────────────────────────────────────────────
st.sidebar.image("https://upload.wikimedia.org/wikipedia/commons/6/63/Databricks_Logo.png", width=180)
st.sidebar.title("🛍️ E-Commerce AI")
st.sidebar.markdown("Built on Databricks Free Edition")
st.sidebar.markdown("---")
page = st.sidebar.radio(
    "Navigate",
    ["💬 Policy Assistant", "📊 Sales Predictions", "📈 Sales Overview"]
)

w, vsc = get_clients()
token = w.config.token
host  = w.config.host

# ── Page 1: Policy Assistant ─────────────────────────────────
if page == "💬 Policy Assistant":
    st.title("💬 E-Commerce Policy Assistant")
    st.markdown("Ask anything about our return, shipping, payment, or loyalty policies.")

    if "messages" not in st.session_state:
        st.session_state.messages = []

    for msg in st.session_state.messages:
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    if question := st.chat_input("Ask a question about our policies..."):
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.write(question)

        with st.chat_message("assistant"):
            with st.spinner("Searching policies..."):
                answer, sources = rag_answer(question, vsc, token, host)
            st.write(answer)
            st.caption(f"📚 Sources: {', '.join(sources)}")

        st.session_state.messages.append({"role": "assistant", "content": answer})

# ── Page 2: Sales Predictions ────────────────────────────────
elif page == "📊 Sales Predictions":
    st.title("📊 ML Order Value Predictions")
    st.markdown("Predictions generated by our RandomForest model, stored in Delta Lake.")

    try:
        df = query_table("ecommerce_demo.sales.order_predictions")
        
        col1, col2, col3 = st.columns(3)
        col1.metric("Total Customers", len(df))
        col2.metric("Avg Predicted Value", f"₹{df['predicted_order_value'].mean():.2f}")
        col3.metric("High Value Customers", len(df[df['value_tier'] == 'High Value']))

        st.markdown("### Predictions Table")
        st.dataframe(
            df[["customer_id", "price", "quantity", "predicted_order_value", "value_tier"]],
            use_container_width=True
        )

        st.markdown("### Value Tier Distribution")
        tier_counts = df["value_tier"].value_counts().reset_index()
        tier_counts.columns = ["Tier", "Count"]
        st.bar_chart(tier_counts.set_index("Tier"))

    except Exception as e:
        st.error(f"Error loading predictions: {e}")

# ── Page 3: Sales Overview ───────────────────────────────────
elif page == "📈 Sales Overview":
    st.title("📈 Sales Overview")
    st.markdown("Live data from your Delta Lake tables.")

    try:
        orders   = query_table("ecommerce_demo.sales.orders")
        products = query_table("ecommerce_demo.sales.products")
        df = orders.merge(products, on="product_id")
        df["order_value"] = df["price"] * df["quantity"]

        col1, col2, col3, col4 = st.columns(4)
        col1.metric("Total Orders", len(df))
        col2.metric("Total Revenue", f"₹{df['order_value'].sum():.2f}")
        col3.metric("Delivered", len(df[df['status'] == 'delivered']))
        col4.metric("Returned", len(df[df['status'] == 'returned']))

        st.markdown("### Revenue by Category")
        cat_rev = df.groupby("category")["order_value"].sum().reset_index()
        st.bar_chart(cat_rev.set_index("category"))

        st.markdown("### Recent Orders")
        st.dataframe(
            df[["order_id", "product_name", "category", "quantity", "order_value", "status"]],
            use_container_width=True
        )

    except Exception as e:
        st.error(f"Error loading sales data: {e}")
